DarkMessiah27/2.PzD-Mission-Template

missions/2PzD_Template_v3_0.VR/customization/loadouts/Japan/gearJpn44.sqf

Jpn44 Changes

---

missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf

Removed Company HQ
Changed Loadouts
#11

Changes to Russian Loadouts

---

missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
missions/2PzD_Template_v3_0.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template_v3_0.VR/customization/geardefs/Generic/gearDefGEN.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/British/gearUK40.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/British/gearUK44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJ40.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJ44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJP40.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJP44Jul.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR39.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR40.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUS42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUS44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSMC42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSMC44.sqf

Moved the Equipment sets to their own gearDef file and changed their names to make it clearer what they do.

Equipment sets

---

missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf

- Adds leader equipment to Squad leaders
- Added Binos to Team leaders
- Removed leader equipment from SWT members

Changed equipment on some leader units

---

compositions/!2PzD_USAB_42/composition.sqe
compositions/!2PzD_USAB_44/composition.sqe
missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB44.sqf
missions/2PzD_Template_v3_0.VR/customization/loadoutsVeh/Generic/vehGearGEN.sqf
missions/2PzD_Template_v3_0.VR/customization/loadoutsVeh/Russian/vehGearRUS.sqf

- Derandomized USAB42 and USAB44 loadouts
- Changed USAB42 and USAB44 compositions
- Removed Heavy MG and MG assistant from squads and replaced with Automatic Machine Gunner and Automatic Machine Gunner Assistant
- Added Machine Gun Team as Heavy Weapons Team
- Add Russian platoon vehicle loadout
Closes #12

De-Randomizing USAB + Russian vehicle loadouts

---

compositions/!2PzD_WHR_44/composition.sqe
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR39.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR40.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR42.sqf
missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR44.sqf
missions/2PzD_Template_v3_0.VR/mission.sqm

- Derandomisation of Wehrmacht loadouts.
- Added Panzerschreck team to WHR44.
- Removed empty layers from mission.sqm.
Closes #9

Derandomisation Wehrmacht

---

missions/2PzD_Template_v3_0.VR/customization/briefing.sqf
missions/2PzD_Template_v3_0.VR/customization/loadoutsVeh/German/vehGearFSJ.sqf

Wrong names

---

missions/2PzD_Template_v3_0.VR/core/functions/fnc_removeAllGear.sqf
missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerAfrica.sqf
missions/2PzD_Template_v3_0.VR/modules/magazine_conversion/functions/FNC_MagazineConversion_CreateChildActions.sqf

This is the last few Areas in the template that points towards FoW Classnames

Clean up of remaining FoW classnames

---

missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/British/VehLoadoutUK.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/German/vehLoadoutWHR.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/US/vehLoadoutUS.sqf

Added Vehicle loadouts for UK
This Closes #35 
Added Vehicle loadouts for US
This Closes #37

Added VehLoadout for the British and US

---

missions/2PzD_Template.VR/customization/loadoutsVeh/British/VehLoadoutUK.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/German/vehLoadoutFSJ.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/German/vehLoadoutWHR.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/Russian/vehLoadoutRUS.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/US/vehLoadoutUS.sqf

Removed Obsolete Documentation from vehLoadouts.

Obsolete Documentation - vehLoadouts

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefGEN.sqf
missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK40.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK44.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR39.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR40.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR42.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR44.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB44.sqf

Added backpack radios to Zug/platoon leaders
Added a Fix to remove Short range radios being added to loadouts where there was a long range radio.

changes to Radios in all loadouts

---

compositions/!2PzD_NOR_40/composition.sqe
compositions/!2PzD_NOR_40/header.sqe
missions/2PzD_Template.VR/customization/geardefs/gearDefNor.sqf
missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadouts/Norwegian/LoadoutNOR40.sqf

Added Norway 1940 Loadout and composition
this closes #75

Added Norway 1940 Loadout and composition

---

compositions/!2PzD_FSJ_40/composition.sqe
compositions/!2PzD_FSJ_44/composition.sqe
compositions/!2PzD_Rus_41/composition.sqe
compositions/!2PzD_Rus_44/composition.sqe
compositions/!2PzD_UK_40/composition.sqe
compositions/!2PzD_UK_44/composition.sqe
compositions/!2PzD_USAB_42/composition.sqe
compositions/!2PzD_USAB_44/composition.sqe
compositions/!2PzD_US_42/composition.sqe
compositions/!2PzD_US_44/composition.sqe
compositions/!2PzD_WHR_39/composition.sqe
compositions/!2PzD_WHR_40/composition.sqe
compositions/!2PzD_WHR_42/composition.sqe
compositions/!2PzD_WHR_44/composition.sqe
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK40.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK44.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutFSJ40.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutFSJ44.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR39.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR40.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR42.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR44.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB44.sqf

Changes to all compositions - Added Recon teams
Changes to US42 - Added back the HMG Team
Removed Some units in SWT compositions where there where more than 2 members.
Changes to all loadouts - Added Recon loadouts
This closes #74

Composition changes and loadout changes

---

missions/2PzD_Template.VR/customization/geardefs/German/gearDefGerLuft.sqf

Fix for FSJ Backpack issue

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK40.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK44.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutFSJ44.sqf
missions/2PzD_Template.VR/customization/loadouts/Norwegian/LoadoutNOR40.sqf

This closes #77 
and adds a comment for GEN_Maps Def under GEN_Default_Equipment_Set

Bino changes

---

compositions/!2PzD_Fin_39/composition.sqe
compositions/!2PzD_Fin_39/header.sqe
compositions/!2PzD_Fin_41/composition.sqe
compositions/!2PzD_Fin_41/header.sqe
missions/2PzD_Template.VR/customization/geardefs.sqf
missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFin.sqf
missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFinRegular.sqf
missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFinWeapons.sqf
missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFinWinter.sqf
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRusWeapons.sqf
missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin39.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin41.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/Finnish/vehLoadoutFIN.sqf

- Added Finnish gearDefs
- Added Finnish Winter War 1939 loadout
- Added Finnish early Continuation War 1941 loadout
- Created Finnish 1939 and 1941 compositions
- Added Russian smoke to gearDefRusWeapons.sqf
Closes #58

Finnish geardef and 1939/1941 loadouts

---

compositions/!2PzD_Rus_39/composition.sqe
compositions/!2PzD_Rus_39/header.sqe
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRus.sqf
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRusRegular.sqf
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRusWinter.sqf
missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus39.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf

- Added Russian 1939 loadout
- Added Russian 1939 composition
- Changed the Russian loadout layout to be in line with those of other loadouts
Closes #84

Added Russian 1939 loadout

---

compositions/!2PzD_NOR_40/composition.sqe
compositions/!2PzD_NOR_40/header.sqe
missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadouts/Norwegian/LoadoutNOR40.sqf

Looking at other factions and parts of the template, it seems we tend to only capitalise the three letters of a country if it's an abbreviation. But if it's just the first three letters of the country's name, only the first letter gets capitalised.

Changes NOR to Nor for Norwegians

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/geardefs/gearDefNor.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK40.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK44.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin39.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin41.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR39.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR40.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR42.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR44.sqf
missions/2PzD_Template.VR/customization/loadouts/Norwegian/LoadoutNOR40.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus39.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB44.sqf

Attempt to standardize SWT leader equipment across the board
Closes #85 
Closes #88

Standardized SWT leader requipment

---

missions/2PzD_Template.VR/customization/loadouts.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/Norwegian/vehLoadoutNOR.sqf

Added Supplies for Squad/Platoon/Resupply
Added Include for Added Loadout in loadouts.sqf
This closes #90

Created vehLoadoutNOR.sqf and Changed loadouts.sqf

---

missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFinRegular.sqf
missions/2PzD_Template.VR/customization/geardefs/Finnish/gearDefFinWinter.sqf
missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/geardefs/gearDefNor.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK40.sqf
missions/2PzD_Template.VR/customization/loadouts/British/loadoutUK44.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin39.sqf
missions/2PzD_Template.VR/customization/loadouts/Finnish/loadoutFin41.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR39.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR40.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR42.sqf
missions/2PzD_Template.VR/customization/loadouts/German/loadoutWHR44.sqf
missions/2PzD_Template.VR/customization/loadouts/Norwegian/LoadoutNOR40.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus39.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUS44.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB42.sqf
missions/2PzD_Template.VR/customization/loadouts/US/loadoutUSAB44.sqf

- Created Finnish recon teams for 39 and 41 loadouts
- Added Helmet_Early_r entry in gearDefFinRegular.sqf
Closes #89

Finnish recon team

---

missions/2PzD_Template.VR/scripts/mapMarkerPrevention.sqf

Removed Group channel from the No No list, to make use of new map mod

Change in mapMarkerPrevention in line with mod changes

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefGEN.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/Generic/vehLoadoutGEN.sqf

Added Geardef for Painkillers
Added Painkillers to Medical Equipmentset
Added Painkillers to Medical Vehicle supplies

Added painkillers to medical loadouts

---

missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRus.sqf
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRusRegular.sqf
missions/2PzD_Template.VR/customization/geardefs/Russian/gearDefRusWinter.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus39.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus41.sqf
missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf

- Changed the Russian tank uniforms to use NF uniforms
- Other smaller changes

Russian tank uniform changes

---

missions/2PzD_Template.VR/init.sqf

Removed unused call from mARMA

Removed Unused Call

---

missions/2PzD_Template.VR/customization/loadouts/Russian/loadoutRus44.sqf

Breaks loadout

---

compositions/!2PzD_UK_40/composition.sqe

My Ocd took over and i had to move the tank slots

---

missions/2PzD_Template.VR/customization/loadoutsVeh/vehLoadoutRUS.sqf

Added two molotovs to Russian vehicle loadouts.

Molotovs for the Russians

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
missions/2PzD_Template.VR/customization/loadoutsVeh/vehLoadoutGEN.sqf

Added more saline to resupply vehicles and split some of the 1000ml bags into 250ml ones. The MedicS has also been given saline.
Closes #116

Increased Saline supplies

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefGEN.sqf
missions/2PzD_Template.VR/customization/loadouts/British_ColdWar/loadoutUK85.sqf

Short range radios were added to the Platoon Leader, Platoon Sergeant, and Section Leader.
Closes #126

Added short range radios to UK85 loadout

---

compositions/!2PzD_UK_85/composition.sqe
missions/2PzD_Template.VR/customization/loadouts/British_ColdWar/loadoutUK85.sqf

- Assign team colours to UK85
- Increase UK85 L42A1 ammo

Assign team colours to UK85

---

compositions/!2PzD_UK_85/composition.sqe
missions/2PzD_Template.VR/customization/geardefs/British_ColdWar/gearDefUKCW.sqf

- Fixed the team colours not automatically assigning at spawn (hopefully, maybe, possibly)
- Changed UK85 Crew uniform as it's the exact same one the enemy uses.

Team colour fix (hopefully)

---

missions/2PzD_Template.VR/core/functions/fnc_removeAllGear.sqf
missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefGEN.sqf
missions/2PzD_Template.VR/customization/loadouts/British_ColdWar/loadoutUK85.sqf

Cleans up the Facewear whitelist a bit and adds the possibilities to have beards. Also removes the short range radio from the UK85 squad leader since he already gets a LR one.

Improve facewear

---

missions/2PzD_Template.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf

Increase to medical supplies
